- sample/Maui.BottomSheet.Sample/Maui.BottomSheet.Sample/MainPage.xaml
- sample/Maui.BottomSheet.Sample/Maui.BottomSheet.Sample/MainViewModel.cs
- sample/Maui.BottomSheet.Sample/Maui.BottomSheet.Sample/Maui.BottomSheet.Sample.csproj
- sample/Maui.BottomSheet.Sample/Maui.BottomSheet.Sample/NewPageA.xaml
- src/Maui.BottomSheet/Maui.BottomSheet/BottomSheetHandler.cs
- src/Maui.BottomSheet/Maui.BottomSheet/ContentPageExtensions.cs
- src/Maui.BottomSheet/Maui.BottomSheet/IBottomSheet.cs
- src/Maui.BottomSheet/Maui.BottomSheet/Maui.BottomSheet.csproj
- src/Maui.BottomSheet/Maui.BottomSheet/Platforms/Android/BottomSheetHandler.cs
- src/Maui.BottomSheet/Maui.BottomSheet/Platforms/Android/MauiBottomSheet.cs
- src/Maui.BottomSheet/Maui.BottomSheet/Platforms/iOS/BottomSheetHandler.cs
- src/Maui.BottomSheet/Maui.BottomSheet/Platforms/iOS/MauiBottomSheet.cs
Fixed BackgroundColor issues and included in sample
> Fixed BackgroundColor issues

- src/Maui.BottomSheet/Maui.BottomSheet/BottomSheet.cs
- src/Maui.BottomSheet/Maui.BottomSheet/IBottomSheet.cs
- src/Maui.BottomSheet/Maui.BottomSheet/Platforms/Android/MauiBottomSheet.cs
- src/Maui.BottomSheet/Maui.BottomSheet/Platforms/iOS/MauiBottomSheet.cs
> Fix open and close event/command calls

- README.md
Tried to copy the XAML sample and noticed the missing quote
And then saw the locale id in the URL. If we remove that it will redirect it to the relevant locale for the user instead of always English.
Great plugin, trying this in a project right now, thanks!
> Very minor README updates

- src/Maui.BottomSheet/Maui.BottomSheet/Platforms/Android/MauiBottomSheet.cs
> fix Android hidden handle is shown initially

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
> [Android] BottomSheet max height calculation incorrect

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
> PeekHeight only correct when ShowHeader is True

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
> [Android] BottomSheet ignores allowed states

- .editorconfig
- README.md
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ShowCasePage.xaml
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ShowCaseViewModel.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheetHeader.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheetHeaderExtensions.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/CloseButtonPosition.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/CloseButtonHandler.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Hosting/MauiAppBuilderExtensions.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetHeader.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheet.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetHeader.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/CloseButton.macios.cs
> Show close button API

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/MauiBottomSheet.macios.cs
> [iOS] Hide/Show header only if BottomSheet is open

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheet.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetHeader.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
> [iOS] Adjust BottomSheet cleanup

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
> [iOS] Background not removed on navigation

- README.md
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/Resources/Styles/Styles.xaml
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheet.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheetHeaderStyle.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheetStyle.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.net.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/CloseButtonHandler.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/IBottomSheet.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetHeader.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/MauiBottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheet.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetHeader.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/CloseButton.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/MauiBottomSheet.macios.cs
> Add API to style BottomSheetHeader

- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ShowCaseViewModel.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.net.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IBottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IBottomSheetNavigationServiceExtensions.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/MauiBottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/MauiBottomSheet.macios.cs
> Add asynchronous navigation methods

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Hosting/IServiceCollectionExtensions.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IBottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IBottomSheetNavigationServiceExtensions.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/MauiBottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/MauiBottomSheet.macios.cs
> Bottom sheet navigation service

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetNavigationService.cs
> Shell IQueryAttributable navigating back

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
> [iOS] Change UIDimmingView color

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetNavigationService.cs
1) First we pass the parameters
2) We perform navigation
fixes #89
> Apply navigation parameters before opening BottomSheet

- README.md
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/Views/CustomBottomSheet.xaml
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheetContent.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheetContentNotSetException.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
> [BottomSheetContent] Simplify usage without requiring ContentTemplate

- README.md
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/MauiProgram.cs
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ViewModels/CustomBottomSheetViewModel.cs
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ViewModels/ShowCaseViewModel.cs
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/Views/CustomBottomSheet.xaml
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/IBottomSheetExtensions.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/MvvmHelpers.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetNavigationParameters.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IConfirmNavigation.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IConfirmNavigationAsync.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetDialog.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetDialogTouchOutsideListener.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheet.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetControllerDelegate.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/MauiBottomSheet.macios.cs
> [Navigation] Confirm navigation

- README.md
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ViewModels/CustomBottomSheetViewModel.cs
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ViewModels/ShellPageViewModel.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/MvvmHelpers.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetStack.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IBottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/INavigationAware.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetDialog.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/MauiBottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/MauiBottomSheet.macios.cs
> [Navigation] Add Navigation Awareness Feature to BottomSheets and ViewModels

- .github/workflows/ci-preview.yml
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample.csproj
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ViewModels/CustomBottomSheetViewModel.cs
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ViewModels/ShowCaseViewModel.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Behaviors/BottomSheetPeekBehavior/BottomSheetPeekBehavior.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/BottomSheetHandler.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Handlers/CloseButtonHandler.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetHeader.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetHeader.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet.csproj
> [Chores] Drop .NET 8 support and add .NET 10 support

- README.md
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/BottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IBottomSheetNavigationService.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Navigation/IBottomSheetNavigationServiceExtensions.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetCallback.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheet.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetControllerDelegate.macios.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
> [Chores] Remove obsolete objects

- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/ViewModels/ShowCaseViewModel.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/ColorDrawableExtensions.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/MauiBottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetUIViewController.macios.cs
> Modal window background fade-in/out animation

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
> [Bug] [Android] BackgroundColor defaulted to White

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Configuration.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/FeatureFlags.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
> [Android] Content doesn't expand to fill available space

- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/FeatureFlags.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheet.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetHeader.android.cs
> [Android] Incorrect PeekHeight calculation for BottomSheets with custom header

- README.md
- sample/Plugin.Maui.BottomSheet.Sample/Plugin.Maui.BottomSheet.Sample/Views/CustomHeaderShowcase.xaml
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheetHeader.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/BottomSheetHeaderExtensions.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/Android/BottomSheetHeader.android.cs
- src/Plugin.Maui.BottomSheet/Plugin.Maui.BottomSheet/Platform/MaciOS/BottomSheetHeader.macios.cs
> [Android] [macos] [ios] Add support for direct content in BottomSheetHeader and refactor content creation logic
